name: paypal_payment
description: Dart package for paypal payment integration in all platforms.
version: 2.0.0+2
repository: https://github.com/code-Shabbir/paypal_payment.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  dio: ^5.7.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  test: ^1.25.8
  freezed: ^2.5.7
  json_serializable: ^6.8.0
